### ISSUE TITLE
Tibetan

### ISSUE THREAD

**Issue by scossu** [virtualvinodh/aksharamukha-python#12]
I have received feedback from Tibetan catalogers about some discrepancies between Aksharamukha and the [ALA-LC Tibetan romanization table](https://www.loc.gov/catdir/cpso/romanization/tibetan.pdf) using Roman (IAST) as the target script. 

Is the intent of Aksharamukha to conform to ALA-LC standards? 

The list of discrepancies is the following (ALA-LC to the left, Aksharamukha to the right): 

```
Vowels:
ཨེ			e					e ( ĕ, æ, ǣ, Others)
ཨོ			o					o (ŏ, Others)
ཨཱ			ā					ā , (ô, others)

Consonants:
ང			nga					ṅa	

Missing Tibetan script in Aksharamukha:
ཅ  ཆ  ཇ	ca cha ja					Missing
ཉ		nya						ña
ཙ		tsa						ca
ཚ		tsha					cha
ཛ		dza						ja
ཝ		wa						va

Missing Tibetan script in Aksharamukha:
ཞ   ཟ   འ	zha za ’a					Missing
ཤ  		sha						śa

Other Letters or Diacritical Marks Used in Words of Non-Tibetan Origin (Log-yig)
ཛྷ		dzha						jha

Missing Tibetan script in Aksharamukha:
Consonant Clusters with Non-joiner to Disambiguate (see Notes 8 and 9)
གཡ   gʹya    ཏྶ     tʹsa    ནྱ    nʹya
```

**Comment by virtualvinodh** [comment]
Fixed. Aksharamukha now supports Tibetan LoC. It is already live.

https://aksharamukha.com/loc

I will update the python package in a couple of days.

V

**Comment by scossu** [comment]
Wonderful. And thanks for the link to the ALA-LC supported languages. I will test when the Python module is updated and let you know.

**Comment by virtualvinodh** [comment]
I have already updated the package.

The test cases for Tibetan are here:

https://github.com/virtualvinodh/aksharamukha-python/blob/main/aksharamukha/test/loc_indic_test_cases.py

I only test for cases that deviate from ISO 15919.  But it should capture all LoC-specific rules.

I'm closing this issue now.  Feel free to open a new issue if you find anything.
