### ISSUE TITLE
Error in Grantha "au"

### ISSUE THREAD

**Issue by akprasad** [virtualvinodh/aksharamukha-python#13]
I believe the Grantha "au" vowel sign should be rendered as 𑌕𑍌 , but 𑌕𑍗 is produced instead.

I don't know Grantha well, so I might be mistaken.

See https://github.com/ambuda-org/vidyut/issues/84 for details.

**Comment by virtualvinodh** [comment]
It's modern convention vs old convention.

If I'm correct, late prints from Tamil Nadu use only the right-hand part.

You'll see publications using both. 

IMHO the modern Malayalam style au should be the default form and the Tamil-style au should be an alternate form, if it helps,

Aksharamukha has an option to toggle this.

![image](https://github.com/virtualvinodh/aksharamukha-python/assets/1050975/1be2adc9-7ab3-45ce-a405-965ff27a6cfd)
