### ISSUE TITLE
Gondi (Gunjala) has no avagraha

### ISSUE THREAD

**Issue by akprasad** [virtualvinodh/aksharamukha-python#14]
When using the online converter and transliterating from SLP1 to Gunjala Gondi, `'` seems to be mapped to an empty string. I'm curious if this is intentional and, if so, what the rationale is. 🙏

**Comment by virtualvinodh** [comment]
The rationale is slightly flimsy.

If a script doesn't have a symbol for Avagraha, I use ' by default for modern scripts and map it to nothing for a historic script. (As you wouldn't expect modern punctuation in historic texts).

IMHO Gunjala Gondi is a form of the Modi script and hence, the mapping.

V
