### ISSUE TITLE
Tirhuta ऱ should (I think) be 𑒩𑓃, not 𑒩

### ISSUE THREAD

**Issue by akprasad** [virtualvinodh/aksharamukha-python#17]
As title. I am not an expert on Tirhuta, so I might be mistaken.

**Comment by virtualvinodh** [comment]
Unfortunately /𑒩𑓃/ is visually Tirhuta /va/ 

![image](https://github.com/virtualvinodh/aksharamukha-python/assets/1050975/939e117e-8ae1-4ffa-95c9-0c1bc7853ff8).

I cannot allow the combination to occur. Hence, the mapping.
