### ISSUE TITLE
Fixed version of Requests dependency causes dependency hell.

### ISSUE THREAD

**Issue by blake-sc** [virtualvinodh/aksharamukha-python#2]
At the moment requirements.txt uses fixed version dependencies:

```
Requests==2.20.1
pykakasi==2.0.6
```

These should be changed to minimum version dependencies so pip can find a version of requests that satisfies other packages too:

```
Requests>=2.20.1
pykakasi>=2.0.6
```

From what I can tell this would not break anything.

**Comment by virtualvinodh** [comment]
This has been fixed. Thanks for letting me know!
